### ISSUE TITLE
Connection aborted

### ISSUE THREAD

**Issue by TomFevrier** [lucasdavid/wikiart#13] opened 2019-02-24 16:58 UTC
Hey!

Every time I try to run the script, I just get a bunch of error messages:
`|- <painter>'s paintings Failed (('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))`

Do you know where it might come from? Is it because the WikiArt server is overloaded?

Thanks!

**Comment by lucasdavid** [comment] 2019-02-26 01:59
Things seem to be working for me. Furthermore, you are the *peer* who reset the connection.
I believe you are having connection problems. Can you try downloading it from a different network?  :thinking:

**Comment by lucasdavid** [comment] 2019-03-01 23:12
@TomFevrier, did you manage to fix it? I'll close this issue if you did.

**Comment by TomFevrier** [comment] 2019-03-01 23:15
No, I still have the same issue...

**Comment by lucasdavid** [comment] 2019-03-02 01:01
Okay. It occurred to me that you might just be experiencing some slow connection issues. Increasing these variables in the settings.py file might help with that:
```py
METADATA_REQUEST_TIMEOUT = 2 * 60
PAINTINGS_REQUEST_TIMEOUT = 5 * 60
```

Additionally, check if you have permission to write on the saving directory (some error handling might be locking the process).

**Closed as completed** 2019-03-06 04:00 UTC

**Comment by lucasdavid** [comment] 2019-03-06 04:02
I'm closing this issue because I can't reproduce this and I gave all advice I could think of.
If you get new info on the problem, feel free to comment or open another isssue.
