### ISSUE TITLE
Converting data identifier from older API

### ISSUE THREAD

**Issue by wemoveon2** [lucasdavid/wikiart#20] opened 2022-06-22 04:23 UTC
Using the paintings data generated using the [new branch](https://github.com/lucasdavid/wikiart/tree/apiv2), I would like to get the details on the painting given by the V2 API [endpoint](https://www.wikiart.org/en/api/2/Painting?id=[paintingId]&imageFormat=[imageFormat]), which offers significantly more details regarding the painting. The problem is that the endpoint requires `id` rather than `contentId`. Is there a way to get the `id` from just the `contentId`?

[Example of desired response from new API](https://www.wikiart.org/en/api/2/Painting?id=5f91703bedc2c90a00d0d522)
[Corresponding information from old API](https://www.wikiart.org/en/App/Painting/ImageJson/9223372032559858107)

The only option I can think of is to use the V2 [search API](https://www.wikiart.org/en/api/2/PaintingSearch?term=saint-jerome-dans-son-cabinet) with the `url` given by the V1 API, but [this is inconsistent and requires parts of the `url` to be omitted to ensure a response](https://www.wikiart.org/en/api/2/PaintingSearch?term=saint-jerome-dans-son-cabinet-detude-1435).

**Comment by lucasdavid** [comment] 2022-06-22 12:13
I'm sorry, I'm not sure what the problem is. You can get the ID by query the list of paintings for a given artist, for example:
```shell
curl https://www.wikiart.org/en/api/2/PaintingsByArtist?id=580b8069edc2c98300cf6e74
```
```json
{
  "data":[
    {"id":"58226baaedc2cb69a0ab172a","title":"Alma Ausente","url":"alma-ausente-1959","artistUrl":"erol-akyavas","artistName":"Erol Akyavaş","artistId":"580b8069edc2c98300cf6e74","completitionYear":1959,"width":750,"image":"https://uploads6.wikiart.org/00105/images/erol-akyavas/alma-ausente-1959.jpg!Large.jpg","height":456},
    {"id":"58226baaedc2cb69a0ab1738","title":"Untıtled","url":"untitled-1959","artistUrl":"erol-akyavas","artistName":"Erol Akyavaş","artistId":"580b8069edc2c98300cf6e74","completitionYear":1959,"width":750,"image":"https://uploads6.wikiart.org/00105/images/erol-akyavas/unt-tled.jpg!Large.jpg","height":379},
    ...
  ],
  ...
}
```
Then you can use these ids to query the details over each image:
```shell
curl https://www.wikiart.org/en/api/2/Painting?id=58226baaedc2cb69a0ab172a
```

This is exactly what this branch is doing, no?
Why do you need `ContentId`?

---

Edit: I see now. You don't want to download everything once again, you just want to update the metadata using what you already downloaded from v1. I don't think I know the answer for this one. :(

**Comment by wemoveon2** [comment] 2022-06-22 20:13
Seems like I was using V1 by mistake, which explains why I was getting the old metadata. 

For the new API, is a session key even a requirement? Everything seems to work despite not having one.

**Comment by lucasdavid** [comment] 2022-06-22 22:02
Yeah, I'm very surprised by that as well...
The problem with V2 (and the reason why I haven't merged with main) is that it blocks us after a few requests, hence downloading everything in a single sit is impossible. I wonder if the limit is different without a session key..?

**Comment by wemoveon2** [comment] 2022-06-23 03:15
It does indeed still block you even if you don't have a session key.

Seems like it switches to tracking IP if you don't have a session key, easily bypassed by using a VPN or proxy.

**Comment by wemoveon2** [comment] 2022-06-23 04:57
https://gist.github.com/Lazza/bbc15561b65c16db8ca8

wrapping this around the fetch and having it close and open a new process for whenever the server returns a 500 might be the fix here.

the ethics of course are questionable at best, i will upload 100gb of the artwork to kaggle whenever i scrape it so hopefully that solves some of it...

**Comment by lucasdavid** [comment] 2022-06-23 12:03
> the ethics of course are questionable at best

Yep. That's a little out of the scope of this repo, unfortunately. Witty workaround, though.

About the session key: I believe throwing requests without a key is the same as using a session key of a free account (400 requests per hour). So if you are not an academic and won't pay for it, then I guess not authenticating is the way to go.

While I have you: For a while now, I wanted to create a tensorflow dataset out of this data and upload it to the catalog (that could be synced with wikiart every now and then); but I never find the time in the PhD life :(
I have some place (university servers) to store it. What is missing is to change the logic in `fetch_artists` to be partial (stops if 500s are happening; restores from where it left when starting) the and the conversion script.
Let me know if you wish (and have the time) to contribute with this part.

Cheers

**Comment by wemoveon2** [comment] 2022-06-24 20:32
> What is missing is to change the logic in fetch_artists to be partial (stops if 500s are happening; restores from where it left when starting) 

Hmm... I'll give it a crack since I need to figure out the logic for catching the 500. Not sure what you meant by 
>the and the conversion script.

What do you think about wrapping all the `response.raise_for_status()` with a `try..except` block to first catch the 500, then when the 500 is caught, writing the `paginationToken` and the work in progress `artist.json` to files. The presence of the `paginationToken` file then can be used as indication for the `artist.json` file being incomplete and to resume using that token. I think this is a relatively simple patch since the URL for `artist.json` doesn't change aside from the token...

`fetch_all_paintings` and `fetch_paintings` has been more of the problem for me since I think the solution would require writing a lot of additional logic for `console.py` or `fetcher.check()`

**Comment by lucasdavid** [comment] 2022-06-24 21:22
I think [these changes](https://github.com/lucasdavid/wikiart/blob/apiv2/wikiart/fetcher.py#L123) do the trick. Let me know what do you think. It's similar to what you suggested, but I'm saving the context in the `_context.json` file instead of overriding `artist.json`. It restarts from where it left off after a 500 and also saves the last query date if it finished without interruptions, so the next run will only requests painters updated after the previous one.

`fetch_all_paintings` is already partial. No need to change it, I believe.

> the and the conversion script.

This regards the script that converts the images into a `tf.data.Dataset`, and used transparently such as:
```py
import tensorflow_datasets as tfds
dataset = tfds.load('wikiart')
```

**Comment by wemoveon2** [comment] 2022-06-24 21:32
I saw your commit as I was about to open a pull request.

```
        response.raise_for_status()
        page = response.json()
      except Exception as error:
        log.write('Error %s' % str(error))
        interrupted = True
        break
```

You may have to catch the 500 as they did [here](https://stackoverflow.com/questions/61463224/when-to-use-raise-for-status-vs-status-code-testing) using `urllib.error.HTTPError` or `requests.exceptions.HTTPError` if [this](https://stackoverflow.com/questions/42379832/status-code-500-not-treated-as-exception) holds true today.

>This regards the script that converts the images into a tf.data.Dataset, and used transparently such as:

Ah, I'm a PyTorch user myself so I won't be much good here.

**Comment by lucasdavid** [comment] 2022-06-24 21:34
You can open the PR fixing this. :)
I see, no problem.

**Comment by lucasdavid** [comment] 2022-06-24 23:10
Well, it's been running for a while now and I'm getting the correct logs. Do you think it's good now and we can close this issue? (I'll wait for it to start downloading the images to make sure everything is working before merging with main).

```py
(wa) ldavid@rider:~/workspace/repos/wikiart$ python wikiart.py --datadir /mnt/files/Workspace/datasets/wikiart/
WikiArt Artwork and Metadata Collector.

License: MIT License (c) 2016

Want to authenticate? You will be asked for your credentials (Y/n): n
Fetching list of artists:
60...60...60...60...60...60...60...60...60...60...60...60...60...60...60...60...60...60...60...60...60...60...60...60...60...60...60...60...Error Response Status Code 500
info: 1708 locally cached painters were loaded
1708 painters (45.29 sec)

Fetching painting data of every artist:
|- Ding Yi (s)
info: 0% done
|- Stickman.......................23 paintings (23.53 sec)
|- Victor Pasmore...................................35 paintings (34.09 sec)
|- Henri Catargi..............................30 paintings (31.72 sec)
|- Mel Bochner...................19 paintings (25.86 sec)
|- Gerard Fromanger...........................27 paintings (42.34 sec)
|- Goran Vojinovic............12 paintings (22.24 sec)
|- Bahia Shehab.............13 paintings (25.69 sec)
|- Edgar Chahine..2 paintings (5.85 sec)
|- Ay-O...............15 paintings (32.14 sec)
|- Guido Viaro.....5 paintings (12.83 sec)
|- Austin Osman Spare............12 paintings (29.25 sec)
|- Nathan Altman........................................40 paintings (103.43 sec)
|- Auguste Rodin..........................................................................................90 paintings (291.58 sec)
|- Claude Georges.................17 paintings (66.56 sec)
|- Antonio Souza............12 paintings (50.96 sec)
|- Raquel Díaz..................18 paintings (76.51 sec)
|- Philip Wilson Steer.........................................41 paintings (182.86 sec)
|- Igor Grabar..................................................................................................................................................................................................194 paintings (721.10 sec)
|- William Tucker...............15 paintings (16.66 sec)
|- Corneliu Baba......................................38 paintings (44.20 sec)
...
```

**Comment by wemoveon2** [comment] 2022-06-24 23:29
Yup, feel free to close the issue.

**Closed as completed** 2022-06-25 03:52 UTC
